souffle: souffle::LVMNullaryRelation Class Reference
souffle::LVMNullaryRelation Class Reference
Interpreter Nullary relation.
#include <LVMRelation.h>
Public Member Functions
iterator begin () const override
Iterator for relation, uses full-order index as default.
bool empty () const override
Check whether relation is empty.
iterator end () const override
bool exists (const RamDomain *tuple) const override
check whether a tuple exists in the relation
std::vector< RamDomain * > extend (const RamDomain *tuple) override
Extend tuple.
void extend (const LVMRelation &rel) override
Extend relation.
void insert (const RamDomain *tuple) override
Insert tuple into nullary relation.
void insert (const LVMRelation &other) override
Merge another relation into this relation.
std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high, size_t indexPosition) const override
Return range iterator.
LVMNullaryRelation (std::string relName, std::vector< std::string > &attributeTypes)
void purge () override
Purge table.
size_t size () const override
Size of nullary is either 0 or 1.
Public Member Functions inherited from souffle::LVMRelation
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
size_t getLevel ()
Get relation level.
const std::string & getName () const
Return relation name.
LVMRelation (size_t relArity, const MinIndexSelection *orderSet, std::string &relName, std::vector< std::string > &attributeTypes)
LVMRelation (const LVMRelation &other)=delete
void setLevel (size_t level)
Set relation level.
virtual ~LVMRelation ()=default
Private Attributes
bool inserted = false
Nullary can hold only one tuple.
LVMIndex nullaryIndex
Nullary index with empty search signature.
Additional Inherited Members
Public Types inherited from souffle::LVMRelation
using iterator = LVMIndex::iterator
Protected Attributes inherited from souffle::LVMRelation
const size_t arity
Arity of relation.
std::vector< std::string > attributeTypeQualifiers
Type of attributes.
size_t level = 0
Relation level.
size_t num_tuples = 0
Number of tuples in relation.
const MinIndexSelection * orderSet
IndexSet.
const std::string relName
Relation name.
Detailed Description
Interpreter Nullary relation.
Definition at line 257 of file LVMRelation.h.
Constructor & Destructor Documentation
souffle::LVMNullaryRelation::LVMNullaryRelation (std::string relName, std::vector< std::string > & attributeTypes) inline
Definition at line 259 of file LVMRelation.h.
             : LVMRelation(0, nullptr, relName, attributeTypes), nullaryIndex(std::vector<int>()) {}
Member Function Documentation
iterator souffle::LVMNullaryRelation::begin () const inline override virtual
Iterator for relation, uses full-order index as default.
Implements souffle::LVMRelation.
Definition at line 297 of file LVMRelation.h.
{
         return nullaryIndex.begin();
     }
bool souffle::LVMNullaryRelation::empty () const inline override virtual
Check whether relation is empty.
Reimplemented from souffle::LVMRelation.
Definition at line 282 of file LVMRelation.h.
{
         return !inserted;
     }
iterator souffle::LVMNullaryRelation::end () const inline override virtual
Implements souffle::LVMRelation.
Definition at line 301 of file LVMRelation.h.
{
         return nullaryIndex.end();
     }
bool souffle::LVMNullaryRelation::exists (const RamDomain * tuple) const inline override virtual
check whether a tuple exists in the relation
Implements souffle::LVMRelation.
Definition at line 292 of file LVMRelation.h.
{
         return inserted;
     }
std::vector<RamDomain*> souffle::LVMNullaryRelation::extend (const RamDomain * tuple) inline override virtual
Extend tuple.
Implements souffle::LVMRelation.
Definition at line 312 of file LVMRelation.h.
{
         std::vector<RamDomain*> newTuples;
         // A standard relation does not generate extra new knowledge on insertion.
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         return newTuples;
     }
void souffle::LVMNullaryRelation::extend (const LVMRelation & rel) inline override virtual
Extend relation.
Implements souffle::LVMRelation.
Definition at line 322 of file LVMRelation.h.
 {}
void souffle::LVMNullaryRelation::insert (const RamDomain * tuple) inline override virtual
Insert tuple into nullary relation.
Implements souffle::LVMRelation.
Definition at line 263 of file LVMRelation.h.
{
         if (!inserted) {
             nullaryIndex.insert(tuple);
         }
         inserted = true;
     }
void souffle::LVMNullaryRelation::insert (const LVMRelation & other) inline override virtual
Merge another relation into this relation.
Implements souffle::LVMRelation.
Definition at line 271 of file LVMRelation.h.
References souffle::LVMRelation::empty(), and souffle::LVMRelation::insert().
{
         if (!other.empty() && !inserted) {
             insert(nullptr);
         }
     }
std::pair<iterator, iterator> souffle::LVMNullaryRelation::lowerUpperBound (const RamDomain * low, const RamDomain * high, size_t indexPosition) const inline override virtual
Return range iterator.
Implements souffle::LVMRelation.
Definition at line 306 of file LVMRelation.h.
References souffle::LVMRelation::begin(), and souffle::LVMRelation::end().
{
         return std::make_pair(begin(), end());
     }
void souffle::LVMNullaryRelation::purge () inline override virtual
Purge table.
Implements souffle::LVMRelation.
Definition at line 287 of file LVMRelation.h.
{
         inserted = false;
     }
size_t souffle::LVMNullaryRelation::size () const inline override virtual
Size of nullary is either 0 or 1.
Reimplemented from souffle::LVMRelation.
Definition at line 278 of file LVMRelation.h.
{
         return inserted == true ? 1 : 0;
     }
Field Documentation
bool souffle::LVMNullaryRelation::inserted = false private
Nullary can hold only one tuple.
Definition at line 326 of file LVMRelation.h.
LVMIndex souffle::LVMNullaryRelation::nullaryIndex private
Nullary index with empty search signature.
Definition at line 329 of file LVMRelation.h.
The documentation for this class was generated from the following file:
LVMRelation.h