souffle: souffle::LVMRelation Class Reference
souffle::LVMRelation Class Reference abstract
#include <LVMRelation.h>
Public Types
using iterator = LVMIndex::iterator
Public Member Functions
virtual iterator begin () const =0
Iterator for relation, uses full-order index as default.
virtual bool empty () const
Check whether relation is empty.
virtual iterator end () const =0
virtual bool exists (const RamDomain *tuple) const =0
check whether a tuple exists in the relation
virtual std::vector< RamDomain * > extend (const RamDomain *tuple)=0
Extend tuple.
virtual void extend (const LVMRelation &rel)=0
Extend relation.
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
size_t getLevel ()
Get relation level.
const std::string & getName () const
Return relation name.
virtual void insert (const RamDomain *tuple)=0
Insert tuple.
virtual void insert (const LVMRelation &other)=0
Merge another relation into this relation.
virtual std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high, size_t indexPosition) const =0
Return range iterator.
LVMRelation (size_t relArity, const MinIndexSelection *orderSet, std::string &relName, std::vector< std::string > &attributeTypes)
LVMRelation (const LVMRelation &other)=delete
virtual void purge ()=0
Purge table.
void setLevel (size_t level)
Set relation level.
virtual size_t size () const
Gets the number of contained tuples.
virtual ~LVMRelation ()=default
Protected Attributes
const size_t arity
Arity of relation.
std::vector< std::string > attributeTypeQualifiers
Type of attributes.
size_t level = 0
Relation level.
size_t num_tuples = 0
Number of tuples in relation.
const MinIndexSelection * orderSet
IndexSet.
const std::string relName
Relation name.
Private Types
using LexOrder = std::vector< int >
Detailed Description
Definition at line 32 of file LVMRelation.h.
Member Typedef Documentation
using souffle::LVMRelation::iterator = LVMIndex::iterator
Definition at line 36 of file LVMRelation.h.
using souffle::LVMRelation::LexOrder = std::vector<int> private
Definition at line 33 of file LVMRelation.h.
Constructor & Destructor Documentation
souffle::LVMRelation::LVMRelation (size_t relArity, const MinIndexSelection * orderSet, std::string & relName, std::vector< std::string > & attributeTypes) inline
Definition at line 38 of file LVMRelation.h.
References ~LVMRelation().
             : arity(relArity), orderSet(orderSet), relName(relName), attributeTypeQualifiers(attributeTypes) {
     }
souffle::LVMRelation::LVMRelation (const LVMRelation & other) delete
virtual souffle::LVMRelation::~LVMRelation () virtual default
Referenced by LVMRelation().
Member Function Documentation
virtual iterator souffle::LVMRelation::begin () const pure virtual
Iterator for relation, uses full-order index as default.
Implemented in souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
Referenced by souffle::LVMRelInterface::begin(), empty(), and souffle::LVMNullaryRelation::lowerUpperBound().
virtual bool souffle::LVMRelation::empty () const inline virtual
Check whether relation is empty.
Reimplemented in souffle::LVMNullaryRelation.
Definition at line 78 of file LVMRelation.h.
References begin(), end(), exists(), extend(), high, insert(), low, lowerUpperBound(), num_tuples, and purge().
Referenced by souffle::LVMNullaryRelation::insert().
{
         return num_tuples == 0;
     }
virtual iterator souffle::LVMRelation::end () const pure virtual
Implemented in souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
Referenced by empty(), souffle::LVMRelInterface::end(), and souffle::LVMNullaryRelation::lowerUpperBound().
virtual bool souffle::LVMRelation::exists (const RamDomain * tuple) const pure virtual
check whether a tuple exists in the relation
Implemented in souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
Referenced by souffle::LVMRelInterface::contains(), empty(), souffle::LVM::execute(), and souffle::LVMIndirectRelation::insert().
virtual std::vector<RamDomain*> souffle::LVMRelation::extend (const RamDomain * tuple) pure virtual
Extend tuple.
Implemented in souffle::LVMEqRelation, souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
Referenced by empty(), souffle::LVMEqRelation::extend(), and souffle::LVMEqRelation::insert().
virtual void souffle::LVMRelation::extend (const LVMRelation & rel) pure virtual
Extend relation.
Implemented in souffle::LVMEqRelation, souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
size_t souffle::LVMRelation::getArity () const inline
Get arity of relation.
Definition at line 68 of file LVMRelation.h.
References arity.
Referenced by souffle::LVM::execute(), souffle::LVMRelInterface::getArity(), souffle::LVMIndirectRelation::getTotalIndexKey(), and souffle::LVMIndirectRelation::insert().
{
         return arity;
     }
std::vector<std::string>& souffle::LVMRelation::getAttributeTypeQualifiers () inline
Get AttributeType for the relation.
Definition at line 48 of file LVMRelation.h.
References attributeTypeQualifiers.
{
         return attributeTypeQualifiers;
     }
size_t souffle::LVMRelation::getLevel () inline
Get relation level.
Definition at line 63 of file LVMRelation.h.
References level.
                       {
         return level;
     }
const std::string& souffle::LVMRelation::getName () const inline
Return relation name.
Definition at line 53 of file LVMRelation.h.
References relName.
Referenced by souffle::LVM::execute().
{
         return relName;
     }
virtual void souffle::LVMRelation::insert (const RamDomain * tuple) pure virtual
Insert tuple.
Implemented in souffle::LVMEqRelation, souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
Referenced by empty(), souffle::LVM::execute(), souffle::LVMRelInterface::insert(), souffle::LVMIndirectRelation::insert(), and souffle::LVMNullaryRelation::insert().
virtual void souffle::LVMRelation::insert (const LVMRelation & other) pure virtual
Merge another relation into this relation.
Implemented in souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
virtual std::pair<iterator, iterator> souffle::LVMRelation::lowerUpperBound (const RamDomain * low, const RamDomain * high, size_t indexPosition) const pure virtual
Return range iterator.
Implemented in souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
Referenced by empty(), and souffle::LVM::execute().
virtual void souffle::LVMRelation::purge () pure virtual
Purge table.
Implemented in souffle::LVMNullaryRelation, and souffle::LVMIndirectRelation.
Referenced by empty(), and souffle::LVMRelInterface::purge().
void souffle::LVMRelation::setLevel (size_t level) inline
Set relation level.
Definition at line 58 of file LVMRelation.h.
References level.
{
         this->level = level;
     }
virtual size_t souffle::LVMRelation::size () const inline virtual
Gets the number of contained tuples.
Reimplemented in souffle::LVMNullaryRelation.
Definition at line 73 of file LVMRelation.h.
References num_tuples.
Referenced by souffle::LVM::execute(), and souffle::LVMRelInterface::size().
{
         return num_tuples;
     }
Field Documentation
const size_t souffle::LVMRelation::arity protected
Arity of relation.
Definition at line 114 of file LVMRelation.h.
Referenced by getArity(), and souffle::LVMIndirectRelation::insert().
std::vector<std::string> souffle::LVMRelation::attributeTypeQualifiers protected
Type of attributes.
Definition at line 126 of file LVMRelation.h.
Referenced by getAttributeTypeQualifiers().
size_t souffle::LVMRelation::level = 0 protected
Relation level.
Definition at line 111 of file LVMRelation.h.
Referenced by getLevel(), and setLevel().
size_t souffle::LVMRelation::num_tuples = 0 protected
Number of tuples in relation.
Definition at line 117 of file LVMRelation.h.
Referenced by empty(), souffle::LVMIndirectRelation::insert(), souffle::LVMIndirectRelation::purge(), and size().
const MinIndexSelection* souffle::LVMRelation::orderSet protected
IndexSet.
Definition at line 120 of file LVMRelation.h.
Referenced by souffle::LVMIndirectRelation::getIndex().
const std::string souffle::LVMRelation::relName protected
Relation name.
Definition at line 123 of file LVMRelation.h.
Referenced by getName().
The documentation for this class was generated from the following file:
LVMRelation.h