souffle: souffle::LVMIndirectRelation Class Reference
souffle::LVMIndirectRelation Class Reference
Interpreter Relation.
#include <LVMRelation.h>
Public Member Functions
iterator begin () const override
Iterator for relation, uses full-order index as default.
iterator end () const override
bool exists (const RamDomain *tuple) const override
check whether a tuple exists in the relation
std::vector< RamDomain * > extend (const RamDomain *tuple) override
Extend tuple.
void extend (const LVMRelation &rel) override
Extend relation.
LVMIndex * getIndex (const SearchSignature &col) const
get index for a given search signature.
LVMIndex * getIndexByPos (int idx) const
get index for a given order.
SearchSignature getTotalIndexKey () const
Obtains a full index-key for this relation.
void insert (const RamDomain *tuple) override
Insert tuple.
void insert (const LVMRelation &other) override
Merge another relation into this relation.
std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high, size_t indexPosition) const override
Return range iterator.
LVMIndirectRelation (size_t relArity, const MinIndexSelection *orderSet, std::string &relName, std::vector< std::string > &attributeTypes)
void purge () override
Purge table.
Public Member Functions inherited from souffle::LVMRelation
virtual bool empty () const
Check whether relation is empty.
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
size_t getLevel ()
Get relation level.
const std::string & getName () const
Return relation name.
LVMRelation (size_t relArity, const MinIndexSelection *orderSet, std::string &relName, std::vector< std::string > &attributeTypes)
LVMRelation (const LVMRelation &other)=delete
void setLevel (size_t level)
Set relation level.
virtual size_t size () const
Gets the number of contained tuples.
virtual ~LVMRelation ()=default
Private Attributes
std::deque< std::unique_ptr< RamDomain[]> > blockList
std::vector< LVMIndex > indices
List of indices.
Static Private Attributes
static const int BLOCK_SIZE = 1024
Size of blocks containing tuples.
Additional Inherited Members
Public Types inherited from souffle::LVMRelation
using iterator = LVMIndex::iterator
Protected Attributes inherited from souffle::LVMRelation
const size_t arity
Arity of relation.
std::vector< std::string > attributeTypeQualifiers
Type of attributes.
size_t level = 0
Relation level.
size_t num_tuples = 0
Number of tuples in relation.
const MinIndexSelection * orderSet
IndexSet.
const std::string relName
Relation name.
Detailed Description
Interpreter Relation.
Definition at line 132 of file LVMRelation.h.
Constructor & Destructor Documentation
souffle::LVMIndirectRelation::LVMIndirectRelation (size_t relArity, const MinIndexSelection * orderSet, std::string & relName, std::vector< std::string > & attributeTypes) inline
Definition at line 134 of file LVMRelation.h.
References souffle::MinIndexSelection::getAllOrders().
             : LVMRelation(relArity, orderSet, relName, attributeTypes) {
         for (auto& order : orderSet->getAllOrders()) {
             indices.push_back(LVMIndex(order));
         }
     }
Member Function Documentation
iterator souffle::LVMIndirectRelation::begin () const inline override virtual
Iterator for relation, uses full-order index as default.
Implements souffle::LVMRelation.
Definition at line 196 of file LVMRelation.h.
{
         return indices[0].begin();
     }
iterator souffle::LVMIndirectRelation::end () const inline override virtual
Implements souffle::LVMRelation.
Definition at line 200 of file LVMRelation.h.
{
         return indices[0].end();
     }
bool souffle::LVMIndirectRelation::exists (const RamDomain * tuple) const inline override virtual
check whether a tuple exists in the relation
Implements souffle::LVMRelation.
Definition at line 190 of file LVMRelation.h.
References souffle::LVMIndex::exists().
{
         LVMIndex* index = getIndex(getTotalIndexKey());
         return index->exists(tuple);
     }
std::vector<RamDomain*> souffle::LVMIndirectRelation::extend (const RamDomain * tuple) inline override virtual
Extend tuple.
Implements souffle::LVMRelation.
Reimplemented in souffle::LVMEqRelation.
Definition at line 212 of file LVMRelation.h.
{
         std::vector<RamDomain*> newTuples;
         // A standard relation does not generate extra new knowledge on insertion.
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         return newTuples;
     }
void souffle::LVMIndirectRelation::extend (const LVMRelation & rel) inline override virtual
Extend relation.
Implements souffle::LVMRelation.
Reimplemented in souffle::LVMEqRelation.
Definition at line 222 of file LVMRelation.h.
 {}
LVMIndex* souffle::LVMIndirectRelation::getIndex (const SearchSignature & col) const inline
get index for a given search signature.
Order are encoded as bits for each column
Definition at line 225 of file LVMRelation.h.
References souffle::MinIndexSelection::getLexOrderNum(), and souffle::LVMRelation::orderSet.
{
         // Special case in provenance program, a 0 searchSignature is considered as a full search
         if (col == 0) {
             return getIndex(getTotalIndexKey());
         }
         return getIndexByPos(orderSet->getLexOrderNum(col));
     }
LVMIndex* souffle::LVMIndirectRelation::getIndexByPos (int idx) const inline
get index for a given order.
Order are encoded as bits for each column
Definition at line 234 of file LVMRelation.h.
{
         return &indices[idx];
     }
SearchSignature souffle::LVMIndirectRelation::getTotalIndexKey () const inline
Obtains a full index-key for this relation.
Definition at line 239 of file LVMRelation.h.
References souffle::LVMRelation::getArity().
{
         return (1 << (getArity())) - 1;
     }
void souffle::LVMIndirectRelation::insert (const RamDomain * tuple) inline override virtual
Insert tuple.
Implements souffle::LVMRelation.
Reimplemented in souffle::LVMEqRelation.
Definition at line 143 of file LVMRelation.h.
References souffle::LVMRelation::arity, souffle::LVMRelation::exists(), i, and souffle::LVMRelation::num_tuples.
Referenced by souffle::LVMEqRelation::extend(), and souffle::LVMEqRelation::insert().
{
         assert(tuple);
         // make existence check
         if (exists(tuple)) {
             return;
         }
         int blockIndex = num_tuples / (BLOCK_SIZE / arity);
         int tupleIndex = (num_tuples % (BLOCK_SIZE / arity)) * arity;
         if (tupleIndex == 0) {
             blockList.push_back(std::make_unique<RamDomain[]>(BLOCK_SIZE));
         }
         RamDomain* newTuple = &blockList[blockIndex][tupleIndex];
         for (size_t i = 0; i < arity; ++i) {
             newTuple[i] = tuple[i];
         }
         // update all indexes with new tuple
         for (auto& cur : indices) {
             cur.insert(newTuple);
         }
         // increment relation size
         num_tuples++;
     }
void souffle::LVMIndirectRelation::insert (const LVMRelation & other) inline override virtual
Merge another relation into this relation.
Implements souffle::LVMRelation.
Definition at line 173 of file LVMRelation.h.
References souffle::LVMRelation::getArity(), and souffle::LVMRelation::insert().
{
         assert(getArity() == other.getArity());
         for (const auto& cur : other) {
             insert(cur);
         }
     }
std::pair<iterator, iterator> souffle::LVMIndirectRelation::lowerUpperBound (const RamDomain * low, const RamDomain * high, size_t indexPosition) const inline override virtual
Return range iterator.
Implements souffle::LVMRelation.
Definition at line 205 of file LVMRelation.h.
{
         auto idx = this->getIndexByPos(indexPosition);
         return idx->lowerUpperBound(low, high);
     }
void souffle::LVMIndirectRelation::purge () inline override virtual
Purge table.
Implements souffle::LVMRelation.
Definition at line 181 of file LVMRelation.h.
References souffle::LVMRelation::num_tuples.
{
         blockList.clear();
         for (auto& cur : indices) {
             cur.purge();
         }
         num_tuples = 0;
     }
Field Documentation
const int souffle::LVMIndirectRelation::BLOCK_SIZE = 1024 static private
Size of blocks containing tuples.
Definition at line 245 of file LVMRelation.h.
std::deque<std::unique_ptr<RamDomain[]> > souffle::LVMIndirectRelation::blockList private
Definition at line 247 of file LVMRelation.h.
std::vector<LVMIndex> souffle::LVMIndirectRelation::indices mutable private
List of indices.
Definition at line 250 of file LVMRelation.h.
The documentation for this class was generated from the following file:
LVMRelation.h