souffle: souffle::LVMIndex Class Reference
souffle::LVMIndex Class Reference
#include <LVMIndex.h>
Data Structures
struct comparator
Public Types
using index_set = btree_multiset< const RamDomain *, comparator, std::allocator< const RamDomain * >, 512 >
using iterator = index_set::iterator
Public Member Functions
iterator begin () const
iterator end () const
std::pair< iterator, iterator > equalRange (const RamDomain *value)
return start and end iterator of an equal range
bool exists (const RamDomain *value)
check whether tuple exists in index
std::pair< iterator, iterator > getIteratorPair () const
return start and end iterator of the index set
void insert (const RamDomain *tuple)
add tuple to the index
template<class Iter >
void insert (const Iter &a, const Iter &b)
add tuples to the index via an iterator
std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high)
return start and end iterator of a range
LVMIndex (LexOrder order)
LVMIndex (const LVMIndex &&index)
const LexOrder & order () const
void print (std::ostream &out) const
enables the index to be printed
void purge ()
purge all hashes of index
Private Types
using LexOrder = std::vector< int >
Private Attributes
index_set::btree_operation_hints< 1 > operation_hints
Operation hints.
index_set set
set storing tuple pointers of table
const LexOrder theOrder
retain the index order used to construct an object of this class
Detailed Description
Definition at line 27 of file LVMIndex.h.
Member Typedef Documentation
using souffle::LVMIndex::index_set = btree_multiset<const RamDomain*, comparator, std::allocator<const RamDomain*>, 512>
Definition at line 68 of file LVMIndex.h.
using souffle::LVMIndex::iterator = index_set::iterator
Definition at line 70 of file LVMIndex.h.
using souffle::LVMIndex::LexOrder = std::vector<int> private
Definition at line 28 of file LVMIndex.h.
Constructor & Destructor Documentation
souffle::LVMIndex::LVMIndex (LexOrder order) inline
Definition at line 72 of file LVMIndex.h.
 : theOrder(std::move(order)), set(comparator(theOrder), comparator(theOrder)) {}
souffle::LVMIndex::LVMIndex (const LVMIndex && index) inline
Definition at line 74 of file LVMIndex.h.
 : theOrder(std::move(index.theOrder)), set(std::move(index.set)) {}
Member Function Documentation
iterator souffle::LVMIndex::begin () const inline
Definition at line 133 of file LVMIndex.h.
{
         return set.begin();
     }
iterator souffle::LVMIndex::end () const inline
Definition at line 137 of file LVMIndex.h.
{
         return set.end();
     }
std::pair<iterator, iterator> souffle::LVMIndex::equalRange (const RamDomain * value) inline
return start and end iterator of an equal range
Definition at line 118 of file LVMIndex.h.
References lowerUpperBound().
{
         return lowerUpperBound(value, value);
     }
bool souffle::LVMIndex::exists (const RamDomain * value) inline
check whether tuple exists in index
Definition at line 100 of file LVMIndex.h.
References operation_hints.
Referenced by souffle::LVMIndirectRelation::exists().
{
         return set.find(value, operation_hints) != set.end();
     }
std::pair<iterator, iterator> souffle::LVMIndex::getIteratorPair () const inline
return start and end iterator of the index set
Definition at line 129 of file LVMIndex.h.
{
         return std::pair<iterator, iterator>(set.begin(), set.end());
     }
void souffle::LVMIndex::insert (const RamDomain * tuple) inline
add tuple to the index
precondition: tuple does not exist in the index
Definition at line 85 of file LVMIndex.h.
References operation_hints.
{
         set.insert(tuple, operation_hints);
     }
template<class Iter > void souffle::LVMIndex::insert (const Iter & a, const Iter & b) inline
add tuples to the index via an iterator
precondition: the tuples do not exist in the index
Definition at line 95 of file LVMIndex.h.
{
         set.insert(a, b);
     };
std::pair<iterator, iterator> souffle::LVMIndex::lowerUpperBound (const RamDomain * low, const RamDomain * high) inline
return start and end iterator of a range
Definition at line 123 of file LVMIndex.h.
References operation_hints.
Referenced by equalRange().
{
         return std::pair<iterator, iterator>(
                 set.lower_bound(low, operation_hints), set.upper_bound(high, operation_hints));
     }
const LexOrder& souffle::LVMIndex::order () const inline
Definition at line 76 of file LVMIndex.h.
References theOrder.
{
         return theOrder;
     }
void souffle::LVMIndex::print (std::ostream & out) const inline
enables the index to be printed
Definition at line 111 of file LVMIndex.h.
{
         set.printStats(out);
         out << "\n";
         set.printTree(out);
     }
void souffle::LVMIndex::purge () inline
purge all hashes of index
Definition at line 105 of file LVMIndex.h.
References operation_hints.
                  {
         set.clear();
         operation_hints.clear();
     }
Field Documentation
index_set::btree_operation_hints<1> souffle::LVMIndex::operation_hints private
Operation hints.
Definition at line 149 of file LVMIndex.h.
Referenced by exists(), insert(), lowerUpperBound(), and purge().
index_set souffle::LVMIndex::set private
set storing tuple pointers of table
Definition at line 146 of file LVMIndex.h.
const LexOrder souffle::LVMIndex::theOrder private
retain the index order used to construct an object of this class
Definition at line 143 of file LVMIndex.h.
Referenced by order().
The documentation for this class was generated from the following file:
LVMIndex.h