souffle: souffle::LVMEqRelation Class Reference
souffle::LVMEqRelation Class Reference
Interpreter Equivalence Relation.
#include <LVMRelation.h>
Public Member Functions
std::vector< RamDomain * > extend (const RamDomain *tuple) override
Find the new knowledge generated by inserting a tuple.
void extend (const LVMRelation &rel) override
Extend this relation with new knowledge generated by inserting all tuples from a relation.
void insert (const RamDomain *tuple) override
Insert tuple.
LVMEqRelation (size_t relArity, const MinIndexSelection *orderSet, std::string relName, std::vector< std::string > &attributeTypes)
Public Member Functions inherited from souffle::LVMIndirectRelation
iterator begin () const override
Iterator for relation, uses full-order index as default.
iterator end () const override
bool exists (const RamDomain *tuple) const override
check whether a tuple exists in the relation
LVMIndex * getIndex (const SearchSignature &col) const
get index for a given search signature.
LVMIndex * getIndexByPos (int idx) const
get index for a given order.
SearchSignature getTotalIndexKey () const
Obtains a full index-key for this relation.
void insert (const LVMRelation &other) override
Merge another relation into this relation.
std::pair< iterator, iterator > lowerUpperBound (const RamDomain *low, const RamDomain *high, size_t indexPosition) const override
Return range iterator.
LVMIndirectRelation (size_t relArity, const MinIndexSelection *orderSet, std::string &relName, std::vector< std::string > &attributeTypes)
void purge () override
Purge table.
Public Member Functions inherited from souffle::LVMRelation
virtual bool empty () const
Check whether relation is empty.
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
size_t getLevel ()
Get relation level.
const std::string & getName () const
Return relation name.
LVMRelation (size_t relArity, const MinIndexSelection *orderSet, std::string &relName, std::vector< std::string > &attributeTypes)
LVMRelation (const LVMRelation &other)=delete
void setLevel (size_t level)
Set relation level.
virtual size_t size () const
Gets the number of contained tuples.
virtual ~LVMRelation ()=default
Additional Inherited Members
Public Types inherited from souffle::LVMRelation
using iterator = LVMIndex::iterator
Protected Attributes inherited from souffle::LVMRelation
const size_t arity
Arity of relation.
std::vector< std::string > attributeTypeQualifiers
Type of attributes.
size_t level = 0
Relation level.
size_t num_tuples = 0
Number of tuples in relation.
const MinIndexSelection * orderSet
IndexSet.
const std::string relName
Relation name.
Detailed Description
Interpreter Equivalence Relation.
Definition at line 336 of file LVMRelation.h.
Constructor & Destructor Documentation
souffle::LVMEqRelation::LVMEqRelation (size_t relArity, const MinIndexSelection * orderSet, std::string relName, std::vector< std::string > & attributeTypes) inline
Definition at line 338 of file LVMRelation.h.
             : LVMIndirectRelation(relArity, orderSet, relName, attributeTypes) {}
Member Function Documentation
std::vector<RamDomain*> souffle::LVMEqRelation::extend (const RamDomain * tuple) inline override virtual
Find the new knowledge generated by inserting a tuple.
Reimplemented from souffle::LVMIndirectRelation.
Definition at line 363 of file LVMRelation.h.
{
         std::vector<RamDomain*> newTuples;
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[0]});
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         newTuples.push_back(new RamDomain[2]{tuple[1], tuple[0]});
         newTuples.push_back(new RamDomain[2]{tuple[1], tuple[1]});
         std::vector<const RamDomain*> relevantStored;
         for (const RamDomain* vals : *this) {
             if (vals[0] == tuple[0] || vals[0] == tuple[1] || vals[1] == tuple[0] || vals[1] == tuple[1]) {
                 relevantStored.push_back(vals);
             }
         }
         for (const auto vals : relevantStored) {
             newTuples.push_back(new RamDomain[2]{vals[0], tuple[0]});
             newTuples.push_back(new RamDomain[2]{vals[0], tuple[1]});
             newTuples.push_back(new RamDomain[2]{vals[1], tuple[0]});
             newTuples.push_back(new RamDomain[2]{vals[1], tuple[1]});
             newTuples.push_back(new RamDomain[2]{tuple[0], vals[0]});
             newTuples.push_back(new RamDomain[2]{tuple[0], vals[1]});
             newTuples.push_back(new RamDomain[2]{tuple[1], vals[0]});
             newTuples.push_back(new RamDomain[2]{tuple[1], vals[1]});
         }
         return newTuples;
     }
void souffle::LVMEqRelation::extend (const LVMRelation & rel) inline override virtual
Extend this relation with new knowledge generated by inserting all tuples from a relation.
Reimplemented from souffle::LVMIndirectRelation.
Definition at line 392 of file LVMRelation.h.
References souffle::LVMRelation::extend(), and souffle::LVMIndirectRelation::insert().
{
         std::vector<RamDomain*> newTuples;
         // store all values that will be implicitly relevant to the those that we will insert
         for (const auto* tuple : rel) {
             for (auto* newTuple : extend(tuple)) {
                 newTuples.push_back(newTuple);
             }
         }
         for (const auto* newTuple : newTuples) {
             LVMIndirectRelation::insert(newTuple);
             delete[] newTuple;
         }
     }
void souffle::LVMEqRelation::insert (const RamDomain * tuple) inline override virtual
Insert tuple.
Reimplemented from souffle::LVMIndirectRelation.
Definition at line 343 of file LVMRelation.h.
References souffle::LVMRelation::extend(), and souffle::LVMIndirectRelation::insert().
{
         // TODO: (pnappa) an eqrel check here is all that appears to be needed for implicit additions
         // TODO: future optimisation would require this as a member datatype
         // brave soul required to pass this quest
         // // specialisation for eqrel defs
         // std::unique_ptr<binaryrelation> eqreltuples;
         // in addition, it requires insert functions to insert into that, and functions
         // which allow reading of stored values must be changed to accommodate.
         // e.g. insert =>  eqRelTuples->insert(tuple[0], tuple[1]);
         // for now, we just have a naive & extremely slow version, otherwise known as a O(n^2) insertion
         // ):
         for (auto* newTuple : extend(tuple)) {
             LVMIndirectRelation::insert(newTuple);
             delete[] newTuple;
         }
     }
The documentation for this class was generated from the following file:
LVMRelation.h